bank_app/urls.py
from django.urls import path
from . import views


app_name = "bank_app"

urlpatterns = [
    path('', views.index, name='index'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('account_details/<int:pk>/', views.account_details, name='account_details'),
    path('transaction_details/<str:transaction>/', views.transaction_details, name='transaction_details'),
    path('make_transfer/', views.make_transfer, name='make_transfer'),
    path('make_external_transfer/', views.make_external_transfer, name='make_external_transfer'),
    path('make_loan/', views.make_loan, name='make_loan'),
    path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('staff_search_partial/', views.staff_search_partial, name='staff_search_partial'),
    path('staff_customer_details/<int:pk>/', views.staff_customer_details, name='staff_customer_details'),
    path('staff_account_list_partial/<int:pk>/', views.staff_account_list_partial, name='staff_account_list_partial'),
    path('staff_account_details/<int:pk>/', views.staff_account_details, name='staff_account_details'),
    path('staff_new_account_partial/<int:user>/', views.staff_new_account_partial, name='staff_new_account_partial'),
    path('staff_new_customer/', views.staff_new_customer, name='staff_new_customer'),
    
    # Receive external transfer
    path('receive_external_transfer/', views.receive_external_transfer, name='receive_external_transfer'),
]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(tf_urls)),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('atm_map/',include('atm_map.urls'), name='atm_map'),
    path('', include('bank_app.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('<str:room_name>/', views.room_view, name='room'),
]

bank_app/views.py
from decimal import Decimal
from secrets import token_urlsafe
# CSRF TOKEN IGNORE
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect, JsonResponse
from django.http import QueryDict
from django.shortcuts import render, reverse, get_object_or_404
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from .forms import TransferForm, UserForm, CustomerForm, NewUserForm, NewAccountForm, ExternalTransferForm
from .models import Account, Ledger, Customer
from .errors import InsufficientFunds
from django.core.exceptions import ObjectDoesNotExist
from .constants import BANK_ID
import requests
import uuid


@login_required
def index(request):
    if request.user.is_staff:
        return HttpResponseRedirect(reverse('bank_app:staff_dashboard'))
    else:
        return HttpResponseRedirect(reverse('bank_app:dashboard'))


# Customer views
@login_required(redirect_field_name=None)
def dashboard(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    accounts = request.user.customer.accounts
    context = {
        'accounts': accounts,
    }
    return render(request, 'bank_app/dashboard.html', context)


@login_required
def account_details(request, pk):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    account = get_object_or_404(Account, user=request.user, pk=pk)
    print(account, '<<<-----------')
    context = {
        'account': account,
    }
    return render(request, 'bank_app/account_details.html', context)


@login_required
def transaction_details(request, transaction):
    movements = Ledger.objects.filter(transaction_id=transaction)
    if not request.user.is_staff:
        print('Good')
        # Updated account__in to --> account_number__in
        if not movements.filter(account_number__in=request.user.customer.accounts):
            print('Bad')
            raise PermissionDenied('Customer is not part of the transaction.')
    context = {
        'movements': movements,
    }
    return render(request, 'bank_app/transaction_details.html', context)


@login_required
def make_transfer(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    if request.method == 'POST':
        transfer_form = TransferForm(request.POST)
        transfer_form.fields['debit_account'].queryset = request.user.customer.accounts

        if transfer_form.is_valid():

            amount = transfer_form.cleaned_data['amount']
            debit_account = Account.objects.get(
                pk=transfer_form.cleaned_data['debit_account'].pk)
            debit_text = transfer_form.cleaned_data['debit_text']
            credit_account = Account.objects.get(
                pk=transfer_form.cleaned_data['credit_account'])
            credit_text = transfer_form.cleaned_data['credit_text']

            # Check if the account transfer is between same account:
            if debit_account == credit_account:
                print('Transfering to same account : debit_account == credit_account')
                context = {
                    'title': 'Transfer Error',
                    'error': 'The receiving account must be different from the sender account.'
                }
                return render(request, 'bank_app/error.html', context)

            try:
                transfer = Ledger.transfer(
                    amount, debit_account, debit_text, credit_account, credit_text)
                return transaction_details(request, transfer)
            except InsufficientFunds:
                context = {
                    'title': 'Transfer Error',
                    'error': 'Insufficient funds for transfer.'
                }
                return render(request, 'bank_app/error.html', context)
    else:
        transfer_form = TransferForm()
    transfer_form.fields['debit_account'].queryset = request.user.customer.accounts
    context = {
        'transfer_form': transfer_form,
    }
    return render(request, 'bank_app/make_transfer.html', context)


@csrf_exempt
@login_required
def make_external_transfer(request):
    form = ExternalTransferForm(request.POST or None)
    form.fields['debit_account'].queryset = request.user.customer.accounts
    if form.is_valid():
        # Store data as a dictionary
        data = request.POST.dict()
        # Add debit_account_bank to data
        data['debit_account_bank'] = BANK_ID

        # Remove csrf token from data
        data.pop('csrfmiddlewaretoken')

        # Try connecting to the receiving bank
        try:
            r = requests.post(
                f'http://localhost:8000/receive_external_transfer/', data=data, timeout=10)
            if r.status_code == requests.codes.ok:
                r = r.json()
                amount = int(data['amount'])
                debit_text = data['debit_text']
                credit_text = data['credit_text']
                # credit account number of the receiver
                credit_account_number = data['credit_account']
                # debit account number of the receiver
                debit_account_number = data['debit_account']
                # ID of the sending
                debit_account_bank_id = data['debit_account_bank']
                # ID of the receiving bank
                credit_account_bank_id = data['credit_account_bank']
                try:
                    transaction_id = r['transaction_id']
                    put_data = {
                        'transaction_id': transaction_id,
                    }
                    # write to ledger
                    Ledger.external_transfer(amount=amount, debit_account_bank_id=debit_account_bank_id, credit_account_bank_id=credit_account_bank_id,
                                             debit_account_number=debit_account_number,
                                             credit_account_number=credit_account_number,
                                             debit_text=debit_text, credit_text=credit_text, transaction_id=transaction_id, is_transaction_succeded=True)

                    try:
                        # after success
                        r = requests.put(
                            f'http://localhost:8000/receive_external_transfer/', data=put_data, timeout=10)
                        if r.status_code == requests.codes.ok:
                            return transaction_details(request, transaction_id)
                    except:
                        context['title'] = 'Transfer Error'
                        context['error'] = 'Receiving bank not responding.'

                except:
                    r = requests.delete(
                        f'http://localhost:8000/receive_external_transfer/', data=put_data, timeout=10)

        except:
            # If request fails
            context = {
                'title': 'Transfer Error',
                'error': 'Receiving bank not responding.'
            }
            return render(request, 'bank_app/error.html', context)

    else:
        print('###### External: Invalid - try again!')

    context = {
        'form': form
    }
    return render(request, 'bank_app/make_external_transfer.html', context)


@login_required
def make_loan(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    if not request.user.customer.can_make_loan:
        context = {
            'title': 'Create Loan Error',
            'error': 'Loan could not be completed.'
        }
        return render(request, 'bank_app/error.html', context)
    if request.method == 'POST':
        request.user.customer.make_loan(
            Decimal(request.POST['amount']), request.POST['name'])
        return HttpResponseRedirect(reverse('bank_app:dashboard'))
    return render(request, 'bank_app/make_loan.html', {})

# Staff views


@login_required
def staff_dashboard(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    return render(request, 'bank_app/staff_dashboard.html')


@login_required
def staff_search_partial(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    search_term = request.POST['search_term']
    customers = Customer.search(search_term)
    context = {
        'customers': customers,
    }
    return render(request, 'bank_app/staff_search_partial.html', context)


@login_required
def staff_customer_details(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    customer = get_object_or_404(Customer, pk=pk)
    if request.method == 'GET':
        user_form = UserForm(instance=customer.user)
        customer_form = CustomerForm(instance=customer)
    elif request.method == 'POST':
        user_form = UserForm(request.POST, instance=customer.user)
        customer_form = CustomerForm(request.POST, instance=customer)
        if user_form.is_valid() and customer_form.is_valid():
            user_form.save()
            customer_form.save()
    new_account_form = NewAccountForm()
    context = {
        'customer': customer,
        'user_form': user_form,
        'customer_form': customer_form,
        'new_account_form': new_account_form,
    }
    return render(request, 'bank_app/staff_customer_details.html', context)


@login_required
def staff_account_list_partial(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    customer = get_object_or_404(Customer, pk=pk)
    accounts = customer.accounts
    context = {
        'accounts': accounts,
    }
    return render(request, 'bank_app/staff_account_list_partial.html', context)


@login_required
def staff_account_details(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

bank_app/templates/bank_app/account_details.html
{% extends "base.html" %}

{% block main %}
<h4 class='mb-3'>Account Details</h4>

<table class='table table-hover'>
    <thead class="thead-dark">
        <tr>
            <th scope="col">Account Number</th>
            <th scope="col">Account Name</th>
            <th scope="col">Balance</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ account.pk }}</td>
            <td>{{ account.name }}</td>
            <td class="amount">{{ account.balance|floatformat:"2" }}</td>
        </tr>
    </tbody>
</table>

<h3 class='mt-5'>Account Transactions</h3>

<table class='table table-hover'>
    <thead class="thead-dark">
        <tr>
            <th>Transaction UID</th>
            <th>Amount</th>
            <th>Date and Time</th>
            <th>Text</th>
        </tr>
    </thead>
    {% for movement in account.movements %}
    <tr>
        <td><a href="{% url 'bank_app:transaction_details' movement.transaction_id %}">{{ movement.transaction_id }}</a>
        </td>
        <td>{{ movement.amount|floatformat:"2" }}</td>
        <td>{{ movement.timestamp }}</td>
        <td>{{ movement.text }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock main %}

bank_app/templates/bank_app/dashboard.html
{% extends "base.html" %}

{% block main %}

<h3>My accounts:</h3>
<table class="table table-hover ">
    <thead class="thead-dark">
    <tr>
        <th>Account Number</th>
        <th>Account Name</th>
    </tr>
    </thead>
    {% for account in accounts %}
    <tbody>
    <tr>
        <td><a href="{% url 'bank_app:account_details' account.pk %}">{{ account.pk }}</a></td>
        <td>{{ account.name }}</td>
    </tr>
    </tbody>
    {% endfor %}
</table>
{% endblock main %}

bank_app/templates/bank_app/error.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {% if user.is_staff %}{{ user.username }}{% else %}{{ user.customer.full_name }}{% endif %}.</p>

<h3>{{ title }}</h3>

<p>{{ error }}</p>

{% endblock main %}

bank_app/templates/bank_app/make_external_transfer.html
{% extends "base.html" %}

{% block main %}
<h3>Transfer money to another bank</h3>
<form action="{% url 'bank_app:make_external_transfer' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ form }}
        <button class="btn btn-primary mt-3">Transfer</button>
    </fieldset>
</form>
{% endblock main %}

bank_app/templates/bank_app/make_loan.html
{% extends "base.html" %}

{% block main %}
<h3>Make a loan</h3>
<form action="{% url 'bank_app:make_loan' %}" method="post">
    {% csrf_token %}
    <fieldset>
    <label for="name">
        Name for loan
    </label>
    <input id="name" name="name" type="text" class="form-control"/>
    <label for="amount">
        Amount
    </label>
    <input id="amount" name="amount"  class="form-control"/>
    <button class="btn btn-primary mt-3">Submit</button>
    </fieldset>
</form>
{% endblock main %}

bank_app/templates/bank_app/make_transfer.html
{% extends "base.html" %}

{% block main %}
<h3>Make a Transfer</h3>
<form action="{% url 'bank_app:make_transfer' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ transfer_form }}
    <button class="btn btn-primary mt-3">Transfer</button>
    </fieldset>
</form>
{% endblock main %}

bank_app/templates/bank_app/staff_account_list_partial.html
<tbody id="account-list">
	{% for account in accounts %}
			<tr>
					<td><a href="{% url 'bank_app:staff_account_details' account.pk %}">{{ account.pk }}</a></td>
					<td>{{ account.name }}</td>
					<td>{{ account.balance|floatformat:"2" }}</td>
			</tr>
	{% endfor %}
	</tbody>
	

bank_app/templates/bank_app/staff_customer_details.html
{% extends "base.html" %}

{% block main %}

<h3>Customer Details</h3>

<form action="{% url 'bank_app:staff_customer_details' customer.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ user_form.as_p }}
        {{ customer_form.as_p }}
    <button class="btn btn-primary mb-3">Update User</button>
    </fieldset>
</form>

<table class="table table-hover mt-3">
    <thead class="thead-dark">
        <tr>
            <th>Account Number</th>
            <th>Account Name</th>
            <th>Account Balance</th>
        </tr>
    </thead>
    <tbody
        id="account-list"
        hx-swap="outerHTML"
        hx-get="{% url 'bank_app:staff_account_list_partial' customer.pk %}"
        hx-trigger="load">
    </tbody>
</table>

<h3 class="mt-5">Create New Account</h3>
<form class="mb-5 pb-5" action="{% url 'bank_app:staff_new_account_partial' customer.user.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ new_account_form.as_p }}
    <button class="btn btn-secondary">Create Account</button>
    </fieldset>
</form>

{% endblock main %}

bank_app/templates/bank_app/staff_dashboard.html
{% extends "base.html" %}

{% block main %}
<h3>Search customer</h3>
<fieldset>
    <input name="search_term"
           placeholder="Enter customer data"
           class="form-control"
           type="text"
           hx-post="{% url 'bank_app:staff_search_partial' %}"
           hx-trigger="keyup changed delay:500ms"
           hx-target="#search-results"
           hx-indicator=".htmx-indicator"
    />
    {% csrf_token %}
</fieldset>

<table class="table table-hover mt-3 ">
    <thead class="thead-dark">
        <th>ID</th>
        <th>Persal ID</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
    </thead>
    <tbody id="search-results">
    </tbody>
</table>

{% endblock main %}

bank_app/templates/bank_app/staff_new_customer.html
{% extends "base.html" %}

{% block main %}
<h3>New Customer</h3>

<form action="{% url 'bank_app:staff_new_customer' %}" method="post">
    {% csrf_token %}
    <fieldset class="pb-4 mb-4">
        {{ new_user_form }}
        {{ customer_form }}
    <button class="btn btn-primary mt-3">Create customer</button>
    </fieldset>
</form>
{% endblock main %}

bank_app/templates/bank_app/staff_search_partial.html
{% for customer in customers %}
<tr>
    <td><a href="{% url 'bank_app:staff_customer_details' customer.pk %}">{{ customer.pk }}</a></td>
    <td>{{ customer.full_name }}</td>
    <td>{{ customer.phone }}</td>
    <td>{{ customer.user.email }}</td>
</tr>
{% endfor %}

bank_app/templates/bank_app/transaction_details.html
{% extends "base.html" %}

{% block main %}

<h3>Transaction Details</h3>
<table class='table table-hover'>
    <thead class="thead-dark">
        <tr>
            <th>Account Number</th>
            <th>UID</th>
            <th>Amount</th>
            <th>Date and Time</th>
            <th>Text</th>
        </tr>
    </thead>
    <tbody>
        {% for movement in movements %}
        <tr>
            <td>{{ movement.account_number }}</td>
            <td>{{ movement.transaction_id }}</td>
            <td>{{ movement.amount|floatformat:"2" }}</td>
            <td>{{ movement.timestamp }}</td>
            <td>{{ movement.transfer_text }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock main %}