atm_map/urls.py
from django.urls import path
from . import views


app_name = "atm_map"

urlpatterns = [
		path('', views.index, name='index'),
]

bank_app/urls.py
from django.urls import path
from . import views


app_name = "bank_app"

urlpatterns = [
    path('', views.index, name='index'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('account_details/<int:pk>/', views.account_details, name='account_details'),
    path('transaction_details/<str:transaction>/', views.transaction_details, name='transaction_details'),
    path('make_transfer/', views.make_transfer, name='make_transfer'),
    path('make_external_transfer/', views.make_external_transfer, name='make_external_transfer'),
    path('make_loan/', views.make_loan, name='make_loan'),
    path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('staff_search_partial/', views.staff_search_partial, name='staff_search_partial'),
    path('staff_customer_details/<int:pk>/', views.staff_customer_details, name='staff_customer_details'),
    path('staff_account_list_partial/<int:pk>/', views.staff_account_list_partial, name='staff_account_list_partial'),
    path('staff_account_details/<int:pk>/', views.staff_account_details, name='staff_account_details'),
    path('staff_new_account_partial/<int:user>/', views.staff_new_account_partial, name='staff_new_account_partial'),
    path('staff_new_customer/', views.staff_new_customer, name='staff_new_customer'),
    
    # Receive external transfer
    path('receive_external_transfer/', views.receive_external_transfer, name='receive_external_transfer'),
]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(tf_urls)),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('atm_map/',include('atm_map.urls'), name='atm_map'),
    path('', include('bank_app.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('<str:room_name>/', views.room_view, name='room'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <title>KEA Bank</title>
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <script defer src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script defer src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
 
    {% load l10n %}
      <header class="mb-4">
 
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'bank_app:index' %}">
            {% if user.is_staff %}
            Bank Staff Portal
            {% else %}
            Bank Customer Portal
            {% endif %}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'bank_app:index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
             
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url 'bank_app:index' %}" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {% if user.is_staff %}
                  Administration
                  {% else %}
                  Transfers and loans
                  {% endif %}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  {% if user.is_staff %}
                  <a class="dropdown-item" href="{% url 'bank_app:staff_new_customer' %}">New Customer</a>
                  <a class="dropdown-item" href="{% url 'admin:index' %}">Django Admin</a>
 
                  {% else %}
                  <a class="dropdown-item" href="{% url 'bank_app:make_transfer' %}">Transfer money</a>
                  <a class="dropdown-item" href="{% url 'bank_app:make_external_transfer' %}">Transfer Money To Other Banks</a>
                  <a class="dropdown-item" href="{% url 'bank_app:make_loan' %}">Make A Loan</a>
 
                  {% endif %}
                </div>
              </li>
              <a class="nav-link" href="{% url 'two_factor:profile' %}">Two factor authentication</a>
              <a class="nav-link" href="{% url 'atm_map:index' %}">Atm locations</a>
              <li class="nav-item">
              <a class="nav-link" href="{% url 'chat:index' %}">Chat<span class="sr-only">(current)</span></a>
              </li>
              <a class="nav-link" href="{% url 'logout' %}">Logout </a>
             
              <!-- {% if user.is_staff %}
              <p>Welcome, {{ user }}.</p>
              {% else %}
              <p>Welcome, {{ user.customer.full_name }}.</p>
              {% endif %} -->
            </ul>
          </div>
        </nav>
 
    </header>
 
    <main class="container-md pb-5 mb-5">
    {% block main %}
    {% endblock main %}
    </main>
 
 
      <footer class="text-center text-white fixed-bottom">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          © 2022 Copyright: Kea Bank
        </div>
 
    </footer>
 
    <script src="https://unpkg.com/htmx.org@1.5.0" integrity="sha384-oGA+prIp5Vchu6we2YkI51UtVzN9Jpx2Z7PnR1I78PnZlN8LkrCT4lqqqmDkyrvI" crossorigin="anonymous"></script>
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    </script>
</body>
</html>